
about :

  name : 'wNameMapper'
  description : 'Simple class to map names from one space to another and vice versa. Options for handling names collisions exist. Use the module to make your program shorter, more readable and to avoid typos.'
  version : '0.5.0'
  enabled : 1
  interpreters :
  - njs >= 8.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools
  - Map names
  - Key by value
  - Translate
  license : MIT
  author : 'Kostiantyn Wandalen <wanalen@willbe.so>'
  contributors :
  - 'Kostiantyn Wandalen <wanalen@willbe.so>'
  npm.name : 'wnamemapper'
  npm.scripts :
    test : 'wtest .run proto/**'
    docgen : 'wdocgen .build proto'
  npm.directories :
    doc : 'doc'
    main : 'proto/dwtools/amid/l5_mapper/NameMapper.s'

path :

  repository : git+https:///github.com/Wandalen/wNameMapper.git
  origins :
   - git+https:///github.com/Wandalen/wNameMapper.git
   - npm:///wnamemapper
  bugtracker : https:///github.com/Wandalen/wNameMapper/issues

step :

  proto.export :
    inherit : module.export
    export : path::export
    tar : 0
    criterion :
      content : 'proto'

  doc.export :
    inherit : module.export
    export : path::doc
    tar : 0
    criterion :
      content : 'doc'

  npm.export :
    inherit : module.export
    export : out.npm
    tar : 0
    criterion :
      content : 'npm'

  npm.publish :
    shell : npm publish

build :

  proto.export :
    criterion :
      content : 'proto'
      export : 1
    steps :
      # - build::debug.raw
      - step::proto.export

  doc.export :
    criterion :
      content : 'doc'
      export : 1
    steps :
      # - build::debug.raw
      - step::doc.export

  npm.export :
    criterion :
      content : 'npm'
      export : 1
    steps :
      # - build::debug.raw
      # - step::npm.export
      - step::npm.publish

  export :

    criterion :
      default : 1
      export : 1
    steps :
      # - build::npm
      - build::proto.export
      # - build::doc.export
